# Generated by Django 5.1.5 on 2025-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(related_name='group_members', to='chat.chatgroup'),
        ),
    ]
