# Generated by Django 5.1.5 on 2025-01-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
